# Generated by Django 4.0 on 2022-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='pic',
            field=models.URLField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.hpdsrTb2AqrQj8PWZbQzkwHaHa%26pid%3DApi&f=1'),
        ),
    ]
